# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a099c07f7049ec2959f3a2b94c50f6179f2bca133b72b1e4e269c34d58a2fbd2d990c65b1a4d6affcf590f98100b57e8d85bdb0f03d63a22e10dd5768b9bebc1

test:
  secret_key_base: 6f6ed0e415b5bdd72d135eddf5dd1f3001021f3b8de5358ab60ddeca2e0bce53cf6222224cdfe6f16a07ec346687331cb7a9c4e283bd0644d6d059e936040667

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
